sudo: required

services:
  - docker

language: Python 

# Use Travis-CI CLI to setup encrypted environment variables
# Docker friendly: http://hub.docker.com/r/ubergarm/travis-ci-cli 
#env:
#  global:
#    - secure: {{ foo }}

# setup build machine
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y --no-install-recommends qemu-user-static binfmt-support 
  - sudo update-binfmts --display qemu-arm

# build code
install:
  - uname -a
  - docker run --rm -it ubergarm/armhf-ubuntu:trusty uname -a

# test code
script:
  - docker build -t rowboat/rowboat1 .
#TBD use environment variables e.g.: owner_name/repo_name:branch_name 
#  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH .

# save/deploy build artifacts
after_sucess:
  - /bin/true
  - docker images
#  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
#  - docker push rowboat/rowboat1

# configure which branches are built
#branches:
#  only:
#    - master

# turn off build email spam and turn slack on channel #github
notifications:
  email: false
  slack:
    secure: oY3Mxu3LEgQaUjHr6bl3IbCU0KcA58EiGb2dDM/JzQyS0gi2GdoYYjCGdno2+y/cB51mMzigJ4GrR8YdfZlmhCDQz4r80ApvxDqkcXDcoBB4/5sI504Pz+pX4PEvaHXSo7Wv1191d59JCCNMwkpGlkYIShY8BmgQfPFL8fKTPV+mp597tg8EzjiUqyZ3iRNbD8kgqdGxAmijQswhaeI5F057Oh9kAXjsWRqUVO6wiQ5w/aPJPeEtWnLaH6WVtg3UMSIbuTs1DqZME7drn6kx8Dfcu+PUVFPEkuVO/7rnRPxMwQQSYuqw4m0GoJQJxpoFvInG12HB+7yirrBDjpoyz/L5xsw4F8XHJY55IAjDvbVLgLYffsEiI6ASQu4G42h7P1vGv7P9L/wdtmZcxFZrDf8T0nWNpat3bLnDfVF5hqs6LgzDOFiRydPhBajpJrU5m89nBL4dKZ/L6eKwiZ4JnfX9VBlLBCJDuxhNnwSJzb+USF33igcf91YwNB0PIsm8Idq8br0PiY8Rt555MaUBRnOV+q7eQCTy11OWMZylLKcM3BYdnQ2FXyeV2eqDt0h68EXjJha8U6eAEh+z5UkfzeZ3G+nEokJ6FLD/MGYngW3q/EPw943cnGHt++/E3RDsk2W7ytSeg+H2e3CvcC49i6DfhUqHeRwSvjYd8Day+NU=
